package com.example.karel.pokemonbattlesimulator;

/**
 * @author Karel
 * @version 1.0
 *
 */

import android.content.res.Resources;
import android.graphics.drawable.Drawable;


public class Pokemon {
    String name;
    int level;
    double weight;
    Type type1;
    Type type2;
    Move[] moves = new Move[4];
    Stats myStats;
    boolean isFainted = false;
    Drawable frontSprite;
    Drawable backSprite;
    StatusEffect myStatus;

    public Pokemon(String name, double weight,  Type type1, Type type2, Move[] moves,
                   Stats myStats, Drawable front, Drawable back) {
        this.name = name;
        this.weight = weight;
        this.type1 = type1;
        this.type2 = type2;
        for (int i = 0; i < 4; i++){
            this.moves[i] = moves[i];
        }
        this.myStats = myStats;
        this.frontSprite = front;
        this.backSprite = back;
    }

    public void setLevel(int newLevel){
        setLevel(newLevel);
    }

    public void faint(){

        isFainted = true;

    }

    @Deprecated
    public void createPokedex(Resources res){
        Type normal = new Type("normal");
        Type fire = new Type("fire");
        Type water = new Type("water");
        Type electric = new Type("electric");
        Type grass = new Type("grass");
        Type ice = new Type("ice");
        Type fighting = new Type("fighting");
        Type poison = new Type("poison");
        Type ground = new Type("ground");
        Type flying = new Type("flying");
        Type psychic = new Type("psychic");
        Type bug = new Type("bug");
        Type rock = new Type("rock");
        Type ghost = new Type("ghost");
        Type dragon = new Type("dragon");
        Type dark = new Type("dark");
        Type steel = new Type("steel");
        Type fairy =  new Type("fairy");
        Type noType = new Type("");
        Drawable bulbasaurFront = res.getDrawable(R.drawable.bulbasaur_front);
        Drawable bulbasaurBack = res.getDrawable(R.drawable.bulbasaur_back);
        Move[] bulbasaurMoves;
        Stats bulbasaurStats = new Stats(1, 45, 49, 49, 65, 65, 45);
        /*1*/ new Pokemon("Bulbasaur", 6.9, grass, poison, bulbasaurMoves, bulbasaurStats, 45, bulbasaurFront, bulbasaurBack);
        Drawable ivysaurFront = res.getDrawable(R.drawable.ivysaur_front);
        Drawable ivysaurBack = res.getDrawable(R.drawable.ivysaur_back);
        Move[] ivysaurMoves;
        Stats ivysaurStats = new Stats(1, 60, 62, 63, 80, 80, 60);
	/*2*/	new Pokemon("Ivysaur", 13.0, grass, poison, ivysaurMoves,ivysaurStats, 60, ivysaurFront, ivysaurBack);
        Drawable venusaurFront = res.getDrawable(R.drawable.venusaur_front);
        Drawable venusaurBack = res.getDrawable(R.drawable.venusaur_back);
        Move[] venusaurMoves;
        Stats venusaurStats = new Stats(1, 80, 82, 83, 100, 100, 80);
	/*3*/	new Pokemon("Venusaur", 100, grass, poison, venusaurMoves, venusaurStats, 80, venusaurFront, venusaurBack);
        Drawable charmanderFront = res.getDrawable(R.drawable.charmander_front);
        Drawable charmanderBack = res.getDrawable(R.drawable.charmander_back);
        Move[] charmanderMoves;
        Stats charmanderStats = new Stats(1, 39, 52, 43, 60, 50, 65);
	/*4*/	new Pokemon("Charmander", 8.5, fire, noType, charmanderMoves, charmanderStats, 39, charmanderFront, charmanderBack);
        Drawable charmeleonFront = res.getDrawable(R.drawable.charmeleon_front);
        Drawable charmeleonBack = res.getDrawable(R.drawable.charmeleon_back);
        Move[] charmeleonMoves;
        Stats charmeleonStats = new Stats(1, 58, 64, 58, 80, 65, 80);
	/*5*/	new Pokemon("Charmeleon", 19.0, fire, noType, charmeleonMoves, charmeleonStats, 58, charmeleonFront, charmeleonBack);
        Drawable charizardFront = res.getDrawable(R.drawable.charizard_front);
        Drawable charizardBack = res.getDrawable(R.drawable.charizard_back);
        Move[] charizardMoves;
        Stats charizardStats = new Stats(1, 78, 84, 78, 109, 85, 100);
	/*6*/	new Pokemon("Charizard", 90.5, fire, flying, charizardMoves, charizardStats, 78, charizardFront, charizardBack);
        Drawable  squirtleFront= res.getDrawable(R.drawable.squirtle_front);
        Drawable squirtleBack = res.getDrawable(R.drawable.squirtle_back);
        Move[] squirtleMoves;
        Stats squirtleStats = new Stats(1, 44, 48, 65, 50, 64, 43);
	/*7*/	new Pokemon("Squirtle", 9.0, water, noType, squirtleMoves, squirtleStats, 44, squirtleFront, squirtleBack);
        Drawable wartortleFront = res.getDrawable(R.drawable.wartortle_front);
        Drawable wartortleBack = res.getDrawable(R.drawable.wartortle_back);
        Move[] wartortleMoves;
        Stats wartortleStats = new Stats(1, 59, 63, 80, 65, 80, 58);
	/*8*/	new Pokemon("Wartortle", 2.5, water, noType, wartortleMoves, wartortleStats, 59, wartortleFront, wartortleBack);
        Drawable blastoiseFront = res.getDrawable(R.drawable.blastoise_front);
        Drawable blastoiseBack = res.getDrawable(R.drawable.blastois_back);
        Move[] blastoiseMoves;
        Stats blastoiseStats = new Stats(1, 79, 83, 100, 85, 105, 78);
	/*9*/	new Pokemon("Blastoise", 85.5, water, noType, blastoiseMoves, blastoiseStats, 79, blastoiseFront, blastoiseBack);
        Drawable caterpieFront = res.getDrawable(R.drawable.caterpie_front);
        Drawable caterpieBack = res.getDrawable(R.drawable.caterpie_back);
        Move[] caterpieMoves;
        Stats caterpieStats = new Stats(1, 45, 30, 35, 20, 20, 45);
	/*10*/	new Pokemon("Caterpie", 2.9, bug, noType, caterpieMoves, caterpieStats, 45, caterpieFront, caterpieBack);
        Drawable metapodFront = res.getDrawable(R.drawable.metapod_front);
        Drawable metapodBack = res.getDrawable(R.drawable.metapod_back);
        Move[] metapodMoves;
        Stats metapodStats = new Stats(1, 50, 20, 55, 25, 25, 30);
	/*11*/	new Pokemon("Metapod", 9.9, bug, noType, metapodMoves, metapodStats, 50, metapodFront, metapodBack);
        Drawable butterfreeFront = res.getDrawable(R.drawable.butterfree_front);
        Drawable butterfreeBack = res.getDrawable(R.drawable.butterfree_back);
        Move[] butterfreeMoves;
        Stats butterfreeStats = new Stats(1, 60, 45, 50, 90, 80, 70);
	/*12*/	new Pokemon("Butterfree", 32, bug, flying, butterfreeMoves, butterfreeStats, 60, butterfreeFront, butterfreeBack);
        Drawable weedleFront = res.getDrawable(R.drawable.weedle_front);
        Drawable weedleBack = res.getDrawable(R.drawable.weedle_back);
        Move[] weedleMoves;
        Stats weedleStats = new Stats(1, 40, 35, 30, 20, 20, 50);
	/*13*/	new Pokemon("Weedle", 3.2, bug, poison, weedleMoves, weedleStats, 40, weedleFront, weedleBack);
        Drawable kakunaFront = res.getDrawable(R.drawable.kakuna_front);
        Drawable kakunaBack = res.getDrawable(R.drawable.kakuna_back);
        Move[] kakunaMoves;
        Stats kakunaStats = new Stats(1, 45, 25, 50, 25, 25, 35);
	/*14*/	new Pokemon("Kakuna", 10, bug, poison, kakunaMoves, kakunaStats, 45, kakunaFront, kakunaBack);
        Drawable beedrillFront = res.getDrawable(R.drawable.beedrill_front);
        Drawable beedrillBack = res.getDrawable(R.drawable.beedrill_back);
        Move[] beedrillMoves;
        Stats beedrillStats = new Stats(1, 65, 90, 40, 45, 80, 75);
	/*15*/	new Pokemon("Beedrill", 29.5, bug, poison, beedrillMoves, beedrillStats, 65, beedrillFront, beedrillBack);
        Drawable pidgeyFront = res.getDrawable(R.drawable.pidgey_front);
        Drawable pidgeyBack = res.getDrawable(R.drawable.pidgey_back);
        Move[] pidgeyMoves;
        Stats pidgeyStats = new Stats(1, 40, 45, 40, 35, 35, 56);
	/*16*/	new Pokemon("Pidgey", 1.8, normal, flying, pidgeyMoves, pidgeyStats, 40, pidgeyFront, pidgeyBack);
        Drawable pidgeottoFront = res.getDrawable(R.drawable.pidgeotto_front);
        Drawable pidgeottoBack = res.getDrawable(R.drawable.pidgeotto_back);
        Move[] pidgeottoMoves;
        Stats pidgeottoStats =  new Stats(1, 63, 60, 55, 50, 50, 71);
	/*17*/	new Pokemon("Pidgeotto", 30, normal, flying, pidgeottoMoves, pidgeottoStats, 63, pidgeottoFront, pidgeottoBack);
        Drawable pidgeotFront = res.getDrawable(R.drawable.pidgeot_front);
        Drawable pidgeotBack = res.getDrawable(R.drawable.pidgeot_back);
        Move[] pidgeotMoves;
        Stats pidgeotStats = new Stats(1, 83, 80, 75, 70, 70, 101);
	/*18*/	new Pokemon("Pidgeot", 39.5, normal, flying, pidgeotMoves, pidgeotStats, 83, pidgeotFront, pidgeotBack);
        Drawable rattataFront = res.getDrawable(R.drawable.rattata_front);
        Drawable rattataBack = res.getDrawable(R.drawable.rattata_back);
        Move[] rattataMoves;
        Stats rattataStats = new Stats(1, 30, 56, 35, 25, 35, 72);
	/*19*/	new Pokemon("Rattata", 3.5, normal, noType, rattataMoves, rattataStats, 30, rattataFront, rattataBack);
        Drawable raticateFront = res.getDrawable(R.drawable.raticate_front);
        Drawable raticateBack = res.getDrawable(R.drawable.raticate_back);
        Move[] raticateMoves;
        Stats raticateStats = new Stats(1, 55, 81, 60, 50, 70, 97);
	/*20*/	new Pokemon("Raticate", 18.5, normal, noType, raticateMoves, raticateStats, 55, raticateFront, raticateBack);
        Drawable spearowFront = res.getDrawable(R.drawable.spearow_front);
        Drawable spearowBack = res.getDrawable(R.drawable.spearow_back);
        Move[] spearowMoves;
        Stats spearowStats = new Stats(1, 40, 60, 30, 31, 31, 70);
	/*21*/	new Pokemon("Spearow", 2, normal, flying, spearowMoves, spearowStats, 40, spearowFront, spearowBack);
        Drawable fearowFront = res.getDrawable(R.drawable.fearow_front);
        Drawable fearowBack = res.getDrawable(R.drawable.fearow_back);
        Move[] fearowMoves;
        Stats fearowStats = new Stats(1, 65, 90, 65, 61, 61, 100);
	/*22*/	new Pokemon("Fearow", 38, normal, flying, fearowMoves, fearowStats, 65, fearowFront, fearowBack);
        Drawable ekansFront = res.getDrawable(R.drawable.ekans_front);
        Drawable ekansBack = res.getDrawable(R.drawable.ekans_back);
        Move[] ekansMoves;
        Stats ekansStats = new Stats(1, 35, 60, 44, 40, 54, 55);
	/*23*/	new Pokemon("Ekans", 6.9, poison, noType, ekansMoves, ekansStats, 35, ekansFront, ekansBack);
        Drawable arbokFront = res.getDrawable(R.drawable.arbok_front);
        Drawable arbokBack = res.getDrawable(R.drawable.arbok_back);
        Move[] arbokMoves;
        Stats arbokStats = new Stats(1, 60, 95, 69, 65, 79, 80);
	/*24*/	new Pokemon("Arbok", 65, poison, noType, arbokMoves, arbokStats, 60, arbokFront, arbokBack);
        Drawable pikachuFront = res.getDrawable(R.drawable.pikachu_front);
        Drawable pikachuBack = res.getDrawable(R.drawable.pikachu_back);
        Move[] pikachuMoves;
        Stats pikachuStats = new Stats(1, 35, 55, 40, 50, 50, 90);
	/*25*/	new Pokemon("Pikachu", 6, electric, noType, pikachuMoves, pikachuStats, 35, pikachuFront, pikachuBack);
        Drawable raichuFront = res.getDrawable(R.drawable.raichu_front);
        Drawable raichuBack = res.getDrawable(R.drawable.raichu_back);
        Move[] raichuMoves;
        Stats raichuStats = new Stats(1, 60, 90, 55, 90, 80, 110);
	/*26*/	new Pokemon("Raichu", 30, electric, noType, raichuMoves, raichuStats, 60, raichuFront, raichuBack);
        Drawable sandshrewFront = res.getDrawable(R.drawable.sandshrew_front);
        Drawable sandshrewBack = res.getDrawable(R.drawable.sandshrew_back);
        Move[] sandshrewMoves;
        Stats sandshrewStats = new Stats(1, 50, 75, 85, 20, 30, 40);
	/*27*/	new Pokemon("Sandshrew", 12, ground, noType, sandshrewMoves, sandshrewStats, 50, sandshrewFront, sandshrewBack);
        Drawable sandslashFront = res.getDrawable(R.drawable.sandslash_front);
        Drawable sandslashBack = res.getDrawable(R.drawable.sandslash_back);
        Move[] sandslashMoves;
        Stats sandslashStats = new Stats(1, 75, 100, 110, 45, 55, 65);
	/*28*/	new Pokemon("Sandslash", 29.5, ground, noType, sandslashMoves, sandslashStats, 75, sandslashFront, sandslashBack);
        Drawable nidoranfFront = res.getDrawable(R.drawable.nidoranf_front);
        Drawable nidoranfBack = res.getDrawable(R.drawable.nidoranf_back);
        Move[] nidoranfMoves;
        Stats nidoranfStats = new Stats(1, 55, 47, 52, 40, 40, 41);
	/*29*/	new Pokemon("NidoranF", 7, poison, noType, nidoranfMoves, nidoranfStats, 55, nidoranfFront, nidoranfBack);
        Drawable nidorinaFront = res.getDrawable(R.drawable.nidorina_front);
        Drawable nidorinaBack = res.getDrawable(R.drawable.nidorina_back);
        Move[] nidorinaMoves;
        Stats nidorinaStats = new Stats(1, 70, 62, 67, 55, 55, 56);
	/*30*/	new Pokemon("Nidorina", 20, poison, noType, nidorinaMoves, nidorinaStats, 70, nidorinaFront, nidorinaBack);
        Drawable nidoqueenFront = res.getDrawable(R.drawable.nidoqueen_front);
        Drawable nidoqueenBack = res.getDrawable(R.drawable.nidoqueen_back);
        Move[] nidoqueenMoves;
        Stats nidoqueenStats = new Stats(1, 90, 92, 87, 75, 85, 76);
	/*31*/	new Pokemon("Nidoqueen", 60, poison, ground, nidoqueenMoves, nidoqueenStats, 90, nidoqueenFront, nidoqueenBack);
        Drawable nidoranmFront = res.getDrawable(R.drawable.nidoranm_front);
        Drawable nidoranmBack = res.getDrawable(R.drawable.nidoranm_back);
        Move[] nidoranmMoves;
        Stats nidoranmStats = new Stats(1, 46, 57, 40, 40, 40, 50);
	/*32*/	new Pokemon("NidoranM", 9, poison, noType, nidoranmMoves, nidoranmStats, 46, nidoranmFront, nidoranmBack);
        Drawable nidorinoFront = res.getDrawable(R.drawable.nidorino_front);
        Drawable nidorinoBack = res.getDrawable(R.drawable.nidorino_back);
        Move[] nidorinoMoves;
        Stats nidorinoStats = new Stats(1, 61, 72, 57, 55, 55, 65);
	/*33*/	new Pokemon("Nidorino", 19.5, poison, noType, nidorinoMoves, nidorinoStats, 61, nidorinoFront, nidorinoBack);
        Drawable nidokingFront = res.getDrawable(R.drawable.nidoking_front);
        Drawable nidokingBack = res.getDrawable(R.drawable.nidoking_back);
        Move[] nidokingMoves;
        Stats nidokingStats = new Stats(1, 81, 102, 77, 85, 75, 85);
	/*34*/	new Pokemon("Nidoking", 62, poison, ground, nidokingMoves, nidokingStats, 81, nidokingFront, nidokingBack);
        Drawable clefairyFront = res.getDrawable(R.drawable.clefairy_front);
        Drawable clefairyBack = res.getDrawable(R.drawable.clefairy_back);
        Move[] clefairyMoves;
        Stats clefairyStats = new Stats(1, 70, 45, 48, 60, 65, 35);
	/*35*/	new Pokemon("Clefairy", 7.5, fairy, noType, clefairyMoves, clefairyStats, 70, clefairyFront, clefairyBack);
        Drawable clefableFront = res.getDrawable(R.drawable.clefable_front);
        Drawable clefableBack = res.getDrawable(R.drawable.clefable_back);
        Move[] clefableMoves;
        Stats clefableStats = new Stats(1, 95, 70, 73, 95, 90, 60);
	/*36*/	new Pokemon("Clefable",  40, fairy, noType, clefableMoves, clefableStats, 95, clefableFront, clefableBack);
        Drawable vulpixFront = res.getDrawable(R.drawable.vulpix_front);
        Drawable vulpixBack = res.getDrawable(R.drawable.vulpix_back);
        Move[] vulpixMoves;
        Stats vulpixStats = new Stats(1, 38, 41, 40, 50, 65, 65);
	/*37*/	new Pokemon("Vulpix", 9.9, fire, noType, vulpixMoves, vulpixStats, 38, vulpixFront, vulpixBack);
        Drawable ninetalesFront = res.getDrawable(R.drawable.ninetails_front);
        Drawable ninetalesBack = res.getDrawable(R.drawable.ninetails_back);
        Move[] ninetalesMoves;
        Stats ninetalesStats = new Stats(1, 73, 76, 75, 81, 100, 100);
	/*38*/	new Pokemon("Ninetales", 19.9, fire, noType, ninetalesMoves, ninetalesStats, 73, ninetalesFront, ninetalesBack);
        Drawable jigglypuffFront = res.getDrawable(R.drawable.jigglypuff_front);
        Drawable jigglypuffBack = res.getDrawable(R.drawable.jigglypuff_back);
        Move[] jigglypuffMoves;
        Stats jigglypuffStats = new Stats(1, 115, 45, 20, 45, 25, 20);
	/*39*/	new Pokemon("Jigglypuff", 5.5, normal, fairy, jigglypuffMoves, jigglypuffStats, 115, jigglypuffFront, jigglypuffBack);
        Drawable wigglytuffFront = res.getDrawable(R.drawable.wigglytuff_front);
        Drawable wigglytuffBack = res.getDrawable(R.drawable.wigglytuff_back);
        Move[] wigglytuffMoves;
        Stats wigglytuffStats = new Stats(1, 140, 70, 45, 85, 50, 45);
	/*40*/	new Pokemon("Wigglytuff", 12, normal, fairy, wigglytuffMoves, wigglytuffStats, 140, wigglytuffFront, wigglytuffBack);
        Drawable zubatFront = res.getDrawable(R.drawable.zubat_front);
        Drawable zubatBack = res.getDrawable(R.drawable.zubat_back);
        Move[] zubatMoves;
        Stats zubatStats = new Stats(1, 40, 45, 35, 30, 40, 55);
	/*41*/	new Pokemon("Zubat", 7.5, poison, flying, zubatMoves, zubatStats, 40, zubatFront, zubatBack);
        Drawable golbatFront = res.getDrawable(R.drawable.golbat_front);
        Drawable golbatBack = res.getDrawable(R.drawable.golbat_back);
        Move[] golbatMoves;
        Stats golbatStats = new Stats(1, 75, 80, 70, 65, 75, 90);
	/*42*/	new Pokemon("Golbat", 55, poison, flying, golbatMoves, golbatStats, 75, golbatFront, golbatBack);
        Drawable oddishFront = res.getDrawable(R.drawable.oddish_front);
        Drawable oddishBack = res.getDrawable(R.drawable.oddish_back);
        Move[] oddishMoves;
        Stats oddishStats = new Stats(1, 45, 50, 55, 75, 65, 30);
	/*43*/	new Pokemon("Oddish", 5.4, grass, poison, oddishMoves, oddishStats, 45, oddishFront, oddishBack);
        Drawable gloomFront = res.getDrawable(R.drawable.gloom_front);
        Drawable gloomBack = res.getDrawable(R.drawable.gloom_back);
        Move[] gloomMoves;
        Stats gloomStats = new Stats(1, 60, 65, 70, 85, 75, 40);
	/*44*/	new Pokemon("Gloom", 8.6, grass, poison, gloomMoves, gloomStats, 60, gloomFront, gloomBack);
        Drawable vileplumeFront = res.getDrawable(R.drawable.vileplume_front);
        Drawable vileplumeBack = res.getDrawable(R.drawable.vileplume_back);
        Move[] vileplumeMoves;
        Stats vileplumeStats = new Stats(1, 75, 80, 85, 110, 90, 50);
	/*45*/	new Pokemon("Vileplume", 18.6, grass, poison, vileplumeMoves, vileplumeStats, 75, vileplumeFront, vileplumeBack);
        Drawable parasFront = res.getDrawable(R.drawable.paras_front);
        Drawable parasBack = res.getDrawable(R.drawable.paras_back);
        Move[] parasMoves;
        Stats parasStats = new Stats(1, 35, 70, 55, 45, 55, 25);
	/*46*/	new Pokemon("Paras", 5.4, bug, grass, parasMoves, parasStats, 35, parasFront, parasBack);
        Drawable parasectFront = res.getDrawable(R.drawable.parasect_front);
        Drawable parasectBack = res.getDrawable(R.drawable.parasect_back);
        Move[] parasectMoves;
        Stats parasectStats = new Stats(1, 60, 95, 80, 60, 80, 30);
	/*47*/	new Pokemon("Parasect", 29.5, bug, grass, parasectMoves, parasectStats, 60, parasectFront, parasectBack);
        Drawable venonatFront = res.getDrawable(R.drawable.venonath_front);
        Drawable venonatBack = res.getDrawable(R.drawable.venonath_back);
        Move[] venonatMoves;
        Stats venonatStats = new Stats(1, 60, 55, 50, 40, 55, 45);
	/*48*/	new Pokemon("Venonat", 30, bug, poison, venonatMoves, venonatStats, 60, venonatFront, venonatBack);
        Drawable venomothFront = res.getDrawable(R.drawable.venomoth_front);
        Drawable venomothBack = res.getDrawable(R.drawable.venomoth_back);
        Move[] venomothMoves;
        Stats venomothStats = new Stats(1, 70, 65, 60, 90, 75, 90);
	/*49*/	new Pokemon("Venomoth", 12.5, bug, poison, venomothMoves, venomothStats, 70, venomothFront, venomothBack);
        Drawable digletFront = res.getDrawable(R.drawable.diglett_front);
        Drawable digletBack = res.getDrawable(R.drawable.diglet_back);
        Move[] digletMoves;
        Stats digletStats = new Stats(1, 10, 55, 25, 35, 45, 95);
	/*50*/	new Pokemon("Diglet", 0.8, ground, noType, digletMoves, digletStats, 10, digletFront, digletBack);
        Drawable dugtrioFront = res.getDrawable(R.drawable.dugtrio_front);
        Drawable dugtrioBack = res.getDrawable(R.drawable.dugtrio_back);
        Move[] dugtrioMoves;
        Stats dugtrioStats = new Stats(1, 35, 100, 50, 50, 70, 120);
	/*51*/	new Pokemon("Dugtiro", 33.3, ground, noType, dugtrioMoves, dugtrioStats, 35, dugtrioFront, dugtrioBack);
        Drawable meowthFront = res.getDrawable(R.drawable.meowth_front);
        Drawable meowthBack = res.getDrawable(R.drawable.meowth_back);
        Move[] meowthMoves;
        Stats meowthStas = new Stats(1, 40, 45, 35, 40, 40, 90);
	/*52*/	new Pokemon("Meowth", 4.2, normal, noType, meowthMoves, meowthStas, 40, meowthFront, meowthBack);
        Drawable persianFront = res.getDrawable(R.drawable.persian_front);
        Drawable persianBack = res.getDrawable(R.drawable.persian_back);
        Move[] persianMoves;
        Stats persianStats = new Stats(1, 65, 70, 60, 65, 65, 115);
	/*53*/	new Pokemon("Persian", 32, normal, noType, persianMoves, persianStats, 65, persianFront, persianBack);
        Drawable psyduckFront = res.getDrawable(R.drawable.psyduck_front);
        Drawable psyduckBack = res.getDrawable(R.drawable.psyduck_back);
        Move[] psyduckMoves;
        Stats psyduckStats = new Stats(1, 50, 52, 48, 65, 50, 55);
	/*54*/	new Pokemon("Psyduck", 19.6, water, noType, psyduckMoves, psyduckStats, 50, psyduckFront, psyduckBack);
        Drawable golduckFront = res.getDrawable(R.drawable.golduck_front);
        Drawable golduckBack = res.getDrawable(R.drawable.golduck_back);
        Move[] golduckMoves;
        Stats golduckStats = new Stats(1, 80, 82, 78, 95, 80, 85);
	/*55*/	new Pokemon("Golduck", 76.6, water, noType, golduckMoves, golduckStats, 80, golduckFront, golduckBack);
        Drawable mankeyFront = res.getDrawable(R.drawable.mankey_front);
        Drawable mankeyBack = res.getDrawable(R.drawable.mankey_back);
        Move[] mankeyMoves;
        Stats mankeyStats = new Stats(1, 40, 80, 35, 35, 45, 70);
	/*56*/	new Pokemon("Mankey", 28, fighting, noType, mankeyMoves, mankeyStats, 40, mankeyFront, mankeyBack);
        Drawable primeapeFront= res.getDrawable(R.drawable.primeape_front);
        Drawable primeapeBack = res.getDrawable(R.drawable.primeape_back);
        Move[] primeapeMoves;
        Stats primeapeStats = new Stats(1, 65, 105, 60, 60, 70, 95);
	/*57*/	new Pokemon("Primeeape", 32, fighting, noType, primeapeMoves, primeapeStats, 60, primeapeFront, primeapeBack);
        Drawable growlitheFront = res.getDrawable(R.drawable.growlithe_front);
        Drawable growlitheBack = res.getDrawable(R.drawable.growlithe_back);
        Move[] growlitheMoves;
        Stats growlitheStats = new Stats(1, 55, 70, 45, 70, 50, 60);
	/*58*/	new Pokemon("Growlithe", 19, fire, noType, growlitheMoves, growlitheStats, 70, growlitheFront, growlitheBack);
        Drawable arcanineFront = res.getDrawable(R.drawable.arcanine_front);
        Drawable arcanineBack = res.getDrawable(R.drawable.arcanine_back);
        Move[] arcanineMoves;
        Stats arcanineStats = new Stats(1, 90, 110, 80, 100, 80, 95);
	/*59*/	new Pokemon("Arcanine", 155, fire, noType, arcanineMoves, arcanineStats, 110, arcanineFront, arcanineBack);
        Drawable poliwagFront = res.getDrawable(R.drawable.poliwag_front);
        Drawable poliwagBack = res.getDrawable(R.drawable.poliwag_back);
        Move[] poliwagMoves;
        Stats poliwagStats = new Stats(1, 40, 50, 40, 40, 40, 90);
	/*60*/	new Pokemon("Poliwag", 12.4, water, noType, poliwagMoves, poliwagStats, 40, poliwagFront, poliwagBack);
        Drawable poliwhirlFront = res.getDrawable(R.drawable.poliwhirl_front);
        Drawable poliwhirlBack = res.getDrawable(R.drawable.poliwhirl_back);
        Move[] poliwhirlMoves;
        Stats poliwhirlStats = new Stats(1, 65, 65, 65, 50, 50, 90);
	/*61*/	new Pokemon("Poliwhirl", 20, water, noType, poliwhirlMoves, poliwhirlStats, 65, poliwhirlFront, poliwhirlBack);
        Drawable poliwrathFront = res.getDrawable(R.drawable.poliwrath_front);
        Drawable poliwrathBack = res.getDrawable(R.drawable.poliwrath_back);
        Move[] poliwrathMoves;
        Stats poliwrathStats = new Stats(1, 90, 95, 95, 70, 90, 70);
	/*62*/	new Pokemon("Poliwrath", 54, water, fighting, poliwrathMoves, poliwrathStats, 90, poliwrathFront, poliwrathBack);
        Drawable abraFront = res.getDrawable(R.drawable.abra_front);
        Drawable abraBack = res.getDrawable(R.drawable.abra_back);
        Move[] abraMoves;
        Stats abraStats = new Stats(1, 25, 20, 15, 105, 55, 90);
	/*63*/	new Pokemon("Abra", 19.5, psychic, noType, abraMoves, abraStats, 25, abraFront, abraBack);
        Drawable kadabraFront = res.getDrawable(R.drawable.kadabra_front);
        Drawable kadabraBack = res.getDrawable(R.drawable.kadabra_back);
        Move[] kadabraMoves;
        Stats kadabraStats = new Stats(1, 40, 35, 30, 120, 70, 105);
	/*64*/	new Pokemon("Kadabra", 56.5, psychic, noType, kadabraMoves, kadabraStats, 40, kadabraFront, kadabraBack);
        Drawable alakazamFront = res.getDrawable(R.drawable.alakazam_front);
        Drawable alakazamBack = res.getDrawable(R.drawable.alakazam_back);
        Move[] alakazamMoves;
        Stats alakazamStats = new Stats(1, 55, 50, 45, 135, 95, 120);
	/*65*/	new Pokemon("Alakazam", 48, psychic, noType, alakazamMoves, alakazamStats, 55, alakazamFront, alakazamBack);
        Drawable machopFront = res.getDrawable(R.drawable.machop_front);
        Drawable machopBack = res.getDrawable(R.drawable.machop_back);
        Move[] machopMoves;
        Stats machopStats = new Stats(1, 70, 80, 50, 35, 35, 35);
	/*66*/	new Pokemon("Machop", 19.5, fighting, noType, machopMoves, machopStats, 70, machopFront, machopBack);
        Drawable machokeFront = res.getDrawable(R.drawable.machoke_front);
        Drawable machokeBack = res.getDrawable(R.drawable.machoke_back);
        Move[] machokeMoves;
        Stats machokeStats = new Stats(1, 80, 100, 70, 50, 60, 45);
	/*67*/	new Pokemon("Machoke", 70.5, fighting, noType, machokeMoves, machokeStats, 80, machokeFront, machokeBack);
        Drawable machampFront = res.getDrawable(R.drawable.machamp_front);
        Drawable machampBack = res.getDrawable(R.drawable.machamp_back);
        Move[] machampMoves;
        Stats machampStats = new Stats(1, 90, 130, 80, 65, 85, 55);
	/*68*/	new Pokemon("Machamp", 130, fighting, noType, machampMoves, machampStats, 90, machampFront, machampBack);
        Drawable bellsproutFront = res.getDrawable(R.drawable.bellsprout_front);
        Drawable bellsproutBack = res.getDrawable(R.drawable.bellsprout_back);
        Move[] bellsproutMoves;
        Stats bellsproutStats = new Stats(1, 50, 75, 35, 70, 30, 40);
	/*69*/	new Pokemon("Bellsprout", 4, grass, poison, bellsproutMoves, bellsproutStats, 50, bellsproutFront, bellsproutBack);
        Drawable weepinbellFront = res.getDrawable(R.drawable.weepinbell_front);
        Drawable weepinbellBack = res.getDrawable(R.drawable.weepinbell_back);
        Move[] weepinbellMoves;
        Stats weepinbellStats = new Stats(1, 65, 90, 50, 85, 45, 55);
	/*70*/	new Pokemon("Weepinbell", 6.4, grass, poison, weepinbellMoves, weepinbellStats, 65, weepinbellFront, weepinbellBack);
        Drawable victreebellFront = res.getDrawable(R.drawable.victreebell_front);
        Drawable victreebellBack = res.getDrawable(R.drawable.victreebell_back);
        Move[] victreebellMoves;
        Stats victreebellStats = new Stats(1, 80, 105, 65, 100, 70, 70);
	/*71*/	new Pokemon("Victreebell", 15.5, grass, poison, victreebellMoves, victreebellStats, 80, victreebellFront, victreebellBack);
        Drawable tentacoolFront = res.getDrawable(R.drawable.tentacool_front);
        Drawable tentacoolBack = res.getDrawable(R.drawable.tentacool_back);
        Move[] tentacoolMoves;
        Stats tentacoolStats = new Stats(1, 40, 40, 35, 50, 100, 70);
	/*72*/	new Pokemon("Tentacool", 45.5, water, poison, tentacoolMoves, tentacoolStats, 40, tentacoolFront, tentacoolBack);
        Drawable tentacruelFront = res.getDrawable(R.drawable.tentacruel_front);
        Drawable tentacruelBack = res.getDrawable(R.drawable.tentacruel_back);
        Move[] tentacruelMoves;
        Stats tentacruelStats = new Stats(1, 80, 70, 65, 80, 120, 100);
	/*73*/	new Pokemon("Tentacruel", 55, water, poison, tentacruelMoves, tentacruelStats, 80, tentacruelFront, tentacruelBack);
        Drawable geodudeFront = res.getDrawable(R.drawable.geodude_front);
        Drawable geodudeBack = res.getDrawable(R.drawable.geodude_back);
        Move[] geodudeMoves;
        Stats geodudeStats = new Stats(1, 40, 80, 100, 30, 30, 20);
	/*74*/	new Pokemon("Geodude", 20, rock, ground, geodudeMoves, geodudeStats, 40, geodudeFront, geodudeBack);
        Drawable gravelerFront = res.getDrawable(R.drawable.graveler_front);
        Drawable gravelerBack = res.getDrawable(R.drawable.graveler_back);
        Move[] gravelerMoves;
        Stats gravelersStats = new Stats(1, 55, 95, 115, 45, 45, 35);
	/*75*/	new Pokemon("Graveler", 105, rock, ground, gravelerMoves, gravelersStats, 55, gravelerFront, gravelerBack);
        Drawable golemFront = res.getDrawable(R.drawable.golem_front);
        Drawable golemBack = res.getDrawable(R.drawable.golem_back);
        Move[] golemMoves;
        Stats golemStats = new Stats(1, 80, 120, 130, 55, 65, 45);
	/*76*/	new Pokemon("Golem", 300, rock, ground, golemMoves, golemStats, 80, golemFront, golemBack);
        Drawable ponytaFront = res.getDrawable(R.drawable.ponyta_front);
        Drawable ponytaBack = res.getDrawable(R.drawable.ponyta_back);
        Move[] ponytaMoves;
        Stats ponytaStats = new Stats(1, 50, 85, 55, 65, 65, 90);
        /*077*/ new Pokemon("Ponyta", 30.0, fire, noType, ponytaMoves, ponytaStats, 50, ponytaFront, ponytaBack);
        Drawable rapidashFront = res.getDrawable(R.drawable.rapidash_front);
        Drawable rapidashBack = res.getDrawable(R.drawable.rapidash_back);
        Move[] rapidashMoves;
        Stats rapidashStats = new Stats(1, 65, 100, 70, 80, 80, 105);
	/*078*/ new Pokemon("Rapidash", 95.0, fire, noType, rapidashMoves, rapidashStats, 65, rapidashFront,rapidashBack);
        Drawable slowpokeFront = res.getDrawable(R.drawable.slowpoke_front);
        Drawable slowpokeBack = res.getDrawable(R.drawable.slowpoke_back);
        Move[] slowpokeMoves;
        Stats slowpokeStats = new Stats (1, 90, 65, 65, 40, 40, 15);
	/*079*/ new Pokemon("Slowpoke", 36.0, water, psychic, slowpokeMoves, slowpokeStats, 90, slowpokeFront, slowpokeBack);
        Drawable slowbroFront = res.getDrawable(R.drawable.slowbro_front);
        Drawable slowbroBack = res.getDrawable(R.drawable.slowbro_back);
        Move[] slowbroMoves;
        Stats slowbroStats = new Stats(1, 95, 75, 110, 100, 80, 30);
	/*080*/ new Pokemon("Slowbro", 78.5, water, psychic, slowbroMoves, slowbroStats, 95, slowbroFront,slowbroBack);
        Drawable magnemiteFront = res.getDrawable(R.drawable.magnemite_front);
        Drawable magnemiteBack = res.getDrawable(R.drawable.magnemite_back);
        Move[] magnemiteMoves;
        Stats magnemiteStats = new Stats(1, 25, 35, 70, 95, 55, 45);
	/*081*/ new Pokemon("Magnemite", 6.0, electric, steel, magnemiteMoves, magnemiteStats,25, magnemiteFront, magnemiteBack);
        Drawable magnetonFront = res.getDrawable(R.drawable.magneton_front);
        Drawable magnetonBack = res.getDrawable(R.drawable.magneton_back);
        Move[] magnetonMoves;
        Stats magnetonStats = new Stats(1, 50, 60, 95, 120, 70, 70);
	/*082*/ new Pokemon("Magneton", 60.0, electric, steel, magnetonMoves, magnetonStats, 50, magnetonFront, magnetonBack);
        Drawable farfetch_dFront = res.getDrawable(R.drawable.farfetch_d_front);
        Drawable farfetch_dBack = res.getDrawable(R.drawable.farfetch_d_back);
        Move[] farfetch_dMoves;
        Stats farfetch_dStats = new Stats(1, 52, 90, 55, 58, 62, 60);
	/*083*/ new Pokemon("Farfetch'd", 15.0, normal, flying, farfetch_dMoves,farfetch_dStats, 52, farfetch_dFront, farfetch_dBack);
        Drawable doduoFront = res.getDrawable(R.drawable.doduo_front);
        Drawable doduoBack = res.getDrawable(R.drawable.doduo_back);
        Move[] doduoMoves;
        Stats doduoStats =  new Stats(1, 35, 85, 45, 35, 35, 75);
	/*084*/ new Pokemon("Doduo", 39.2, normal, flying, doduoMoves, doduoStats, 35, doduoFront, doduoBack);
        Drawable dodrioFront = res.getDrawable(R.drawable.dodrio_front);
        Drawable dodrioBack = res.getDrawable(R.drawable.dodrio_back);
        Move[] dodrioMoves;
        Stats dodrioStats = new Stats(1, 60, 110, 70, 60, 60, 110);
	/*085*/ new Pokemon("Dodrio", 85.2, normal, flying, dodrioMoves, dodrioStats, 60, dodrioFront, dodrioBack);
        Drawable seelFront = res.getDrawable(R.drawable.seel_front);
        Drawable seelBack = res.getDrawable(R.drawable.seel_back);
        Move[] seelMoves;
        Stats seelStats = new Stats(1, 65, 45, 55, 45, 70, 45);
	/*086*/ new Pokemon("Seel", 90.0, water, noType, seelMoves, seelStats, 65, seelFront, seelBack);
        Drawable dewgongFront = res.getDrawable(R.drawable.dewgong_front);
        Drawable dewgongBack = res.getDrawable(R.drawable.dewgong_back);
        Move[] dewgongMoves;
        Stats dewgongStats = new Stats(1, 90, 70, 80, 70, 95, 70);
	/*087*/ new Pokemon("Dewgong", 120.0, water, ice, dewgongMoves, dewgongStats, 90, dewgongFront, dewgongBack);
        Drawable grimerFront = res.getDrawable(R.drawable.grimer_front);
        Drawable grimerBack = res.getDrawable(R.drawable.grimer_back);
        Move[] grimerMoves;
        Stats grimerStats = new Stats(1, 80, 80, 50, 40, 50, 25);
	/*088*/ new Pokemon("Grimer", 30.0, poison, noType, grimerMoves,grimerStats, 80, grimerFront, grimerBack);
        Drawable mukFront = res.getDrawable(R.drawable.muk_front);
        Drawable mukBack = res.getDrawable(R.drawable.muk_back);
        Move[] mukMoves;
        Stats mukStats = new Stats(1, 105, 105, 75, 65, 100, 50);
	/*089*/ new Pokemon("Muk", 30.0, poison, noType, mukMoves, mukStats, 105, mukFront,mukBack);
        Drawable shellderFront = res.getDrawable(R.drawable.shellder_front);
        Drawable shellderBack = res.getDrawable(R.drawable.shellder_back);
        Move[] shellderMoves;
        Stats shellderStats = new Stats(1, 30, 65, 100, 45, 25, 40);
	/*090*/ new Pokemon("shellder", 4.0, water, noType, shellderMoves, shellderStats, 30, shellderFront, shellderBack);
        Drawable cloysterFront = res.getDrawable(R.drawable.cloyster_front);
        Drawable cloysterBack = res.getDrawable(R.drawable.cloyster_back);
        Move[] cloysterMoves;
        Stats cloysterStats = new Stats(1, 50, 95, 180, 85, 45, 70);
	/*091*/ new Pokemon("Cloyset", 132.5, water, ice, cloysterMoves, cloysterStats, 50, cloysterFront, cloysterBack);
        Drawable gastlyFront = res.getDrawable(R.drawable.gastly_front);
        Drawable gastlyBack = res.getDrawable(R.drawable.gastly_back);
        Move[] gastlyMoves;
        Stats gastlyStats = new Stats(1, 30, 35, 30, 100, 35, 80);
	/*092*/ new Pokemon("Gastly", 0.1, ghost, poison, gastlyMoves, gastlyStats, 30, gastlyFront, gastlyBack);
        Drawable haunterFront = res.getDrawable(R.drawable.haunter_front);
        Drawable haunterBack = res.getDrawable(R.drawable.haunter_back);
        Move[] haunterMoves;
        Stats haunterStats = new Stats(1, 45, 50, 45, 115, 55, 95);
	/*093*/ new Pokemon("Haunter", 0.1, ghost, poison, haunterMoves, haunterStats, 45, haunterFront, haunterBack);
        Drawable gengarFront = res.getDrawable(R.drawable.gengar_front);
        Drawable gengarBack = res.getDrawable(R.drawable.gengar_back);
        Move[] gengarMoves;
        Stats gengarStats = new Stats(1, 60, 65, 60, 130, 75, 110);
	/*094*/ new Pokemon("Gengar", 40.5, ghost, poison, gengarMoves, gengarStats, 60, gengarFront, gengarBack);
        Drawable onixFront = res.getDrawable(R.drawable.onix_front);
        Drawable onixBack = res.getDrawable(R.drawable.onix_back);
        Move[] onixMoves;
        Stats onixStats = new Stats(1, 35, 45, 160, 30, 45, 70);
	/*095*/ new Pokemon("Onix", 210.0, rock, ground, onixMoves, onixStats, 35, onixFront, onixBack);
        Drawable drowzeeFront = res.getDrawable(R.drawable.drowzee_front);
        Drawable drowzeeBack = res.getDrawable(R.drawable.drowzee_back);
        Move[] drowzeeMoves;
        Stats drowzeeStats = new Stats(1, 60, 48, 45, 43, 90, 42);
	/*096*/ new Pokemon("Drowzee", 32.4, psychic, noType, drowzeeMoves, drowzeeStats, 60, drowzeeFront, drowzeeBack);
        Drawable hypnoFront = res.getDrawable(R.drawable.hypno_front);
        Drawable hypnoBack = res.getDrawable(R.drawable.hypno_back);
        Move[] hypnoMoves;
        Stats hypnoStats = new Stats(1, 85, 73, 70, 73, 115, 67);
	/*097*/ new Pokemon("Hypno", 75.6, psychic, noType, hypnoMoves, hypnoStats, 85, hypnoFront, hypnoBack);
        Drawable krabbyFront = res.getDrawable(R.drawable.krabby_front);
        Drawable krabbyBack = res.getDrawable(R.drawable.krabby_back);
        Move[] krabbyMoves;
        Stats krabbyStats = new Stats(1, 30, 105, 90, 25, 25, 50);
	/*098*/ new Pokemon("Krabby", 6.5, water, noType, krabbyMoves, krabbyStats, 30, krabbyFront, krabbyBack);
        Drawable kinglerFront = res.getDrawable(R.drawable.kingler_front);
        Drawable kinglerBack = res.getDrawable(R.drawable.kingler_back);
        Move[] kinglerMoves;
        Stats kinglerStats = new Stats(1, 55, 130, 115, 50, 50, 75);
	/*099*/ new Pokemon("Kingler", 60.0, water, noType, kinglerMoves, kinglerStats, 55, kinglerFront, kinglerBack);
        Drawable voltorbFront = res.getDrawable(R.drawable.voltorb_font);
        Drawable voltorbBack = res.getDrawable(R.drawable.voltorb_back);
        Move[] voltorbMoves;
        Stats voltorbStats = new Stats(1, 40, 30, 50, 55, 55, 100);
	/*100*/ new Pokemon("Voltorb", 10.4, electric, noType, voltorbMoves, voltorbStats, 40, voltorbFront, voltorbBack);
        Drawable electrodeFront = res.getDrawable(R.drawable.electrode_front);
        Drawable electrodeBack = res.getDrawable(R.drawable.electrode_back);
        Move[] electrodeMoves;
        Stats electrodeStats = new Stats(1, 60, 50, 70, 80, 80, 150);
	/*101*/ new Pokemon("Electrode", 66.6, electric, noType, electrodeMoves, electrodeStats, 60, electrodeFront, electrodeBack);
        Drawable exeggcuteFront = res.getDrawable(R.drawable.exeggcute_front);
        Drawable exeggcuteBack = res.getDrawable(R.drawable.exeggcute_back);
        Move[] exeggcuteMoves;
        Stats exeggcuteStats = new Stats(1, 60, 40, 80, 60, 45, 40);
	/*102*/ new Pokemon("Exeggcute", 2.5, grass, psychic, exeggcuteMoves, exeggcuteStats, 60, exeggcuteFront, exeggcuteBack);
        Drawable exeggutorFront = res.getDrawable(R.drawable.exeggutor_front);
        Drawable exeggutorBack = res.getDrawable(R.drawable.exeggutor_back);
        Move[] exeggutorMoves;
        Stats exeggutorStats = new Stats(1, 95, 95, 85, 125, 75, 55);
	/*103*/ new Pokemon("Exeggutor", 120.0, grass, psychic, exeggutorMoves, exeggutorStats, 95, exeggutorFront,exeggutorBack);
        Drawable cuboneFront = res.getDrawable(R.drawable.cubone_front);
        Drawable cuboneBack = res.getDrawable(R.drawable.cubone_back);
        Move[] cuboneMoves;
        Stats cuboneStats = new Stats(1, 50, 50, 95, 40, 50, 35);
	/*104*/ new Pokemon("Cubone", 6.5, ground, noType, cuboneMoves, cuboneStats, 50, cuboneFront, cuboneBack);
        Drawable marowakFront = res.getDrawable(R.drawable.marowak_front);
        Drawable marowakBack = res.getDrawable(R.drawable.marowak_back);
        Move[] marowakMoves;
        Stats marowakStats = new Stats(1, 60, 80, 110, 50, 80, 45);
	/*105*/ new Pokemon("Marowak", 45.0, ground, noType, marowakMoves, marowakStats, 60, marowakFront, marowakBack);
        Drawable hitmonleeFront = res.getDrawable(R.drawable.hitmonlee_front);
        Drawable hitmonleeBack = res.getDrawable(R.drawable.hitmonlee_back);
        Move[] hitmonleeMoves;
        Stats hitmonleeStats = new Stats(1, 50, 120, 53, 35, 110, 87);
	/*106*/ new Pokemon("Hitmonlee", 49.8, fighting, noType, hitmonleeMoves, hitmonleeStats, 50, hitmonleeFront, hitmonleeBack);
        Drawable hitmonchanFront = res.getDrawable(R.drawable.hitmonchan_front);
        Drawable hitmonchanBack = res.getDrawable(R.drawable.hitmonchan_back);
        Move[] hitmonchanMoves;
        Stats hitmonchanStats = new Stats(1, 50, 105, 79, 35, 110, 76);
	/*107*/ new Pokemon("Hitmonchan", 50.2, fighting, noType, hitmonchanMoves,hitmonchanStats,50, hitmonchanFront, hitmonchanBack);
        Drawable lickingtungFront = res.getDrawable(R.drawable.lickitung_front);
        Drawable lickingtungBack = res.getDrawable(R.drawable.lickitung_back);
        Move[] lickitungMoves;
        Stats lickitungStats = new Stats(1, 90, 55, 75, 60, 75, 30);
	/*108*/ new Pokemon("Lickitung", 65.5,normal, noType, lickitungMoves, lickitungStats, 90, lickingtungFront, lickingtungBack);
        Drawable koffingFront = res.getDrawable(R.drawable.koffing_front);
        Drawable koffingBack = res.getDrawable(R.drawable.koffing_back);
        Move[] koffingMoves;
        Stats koffingStats = new Stats(1, 40, 65, 95, 60, 45, 35);
	/*109*/ new Pokemon("Koffing", 1.0, poison, noType, koffingMoves, koffingStats, 40, koffingFront, koffingBack);
        Drawable weezingFront = res.getDrawable(R.drawable.weezing_front);
        Drawable weezingBack = res.getDrawable(R.drawable.weezing_back);
        Move[] weezingMoves;
        Stats weezingStats = new Stats(1, 65, 90, 120, 85, 70, 60);
 	/*110*/ new Pokemon("Weezing", 9.5, poison, noType, weezingMoves,weezingStats,65, weezingFront,weezingBack);
        Drawable rhyhornFront = res.getDrawable(R.drawable.rhyhorn_front);
        Drawable rhyhornBack = res.getDrawable(R.drawable.rhyhorn_back);
        Move[] rhyhornMoves;
        Stats rhyhornStats = new Stats(1, 80, 85, 95, 30, 30, 25);
	/*111*/ new Pokemon("Rhyhorn", 115.0, ground, rock, rhyhornMoves, rhyhornStats, 80, rhyhornFront, rhyhornBack);
        Drawable rhydonFront = res.getDrawable(R.drawable.rhydon_front);
        Drawable rhydonBack = res.getDrawable(R.drawable.rhydon_back);
        Move[] rhydonMoves;
        Stats rhydonStats = new Stats(1, 105, 130, 120, 45, 45, 40);
	/*112*/ new Pokemon("Rhydon", 120.0, ground, rock, rhydonMoves, rhydonStats, 105, rhydonFront, rhydonBack);
        Drawable chanseyFront = res.getDrawable(R.drawable.chansey_front);
        Drawable chanseyBack = res.getDrawable(R.drawable.chansey_back);
        Move[] chanseyMoves;
        Stats chanseyStats = new Stats(1, 250, 5, 5, 35, 105, 50);
	/*113*/ new Pokemon("Chansey", 34.6, normal, noType, chanseyMoves, chanseyStats,250, chanseyFront, chanseyBack);
        Drawable tangelaFront = res.getDrawable(R.drawable.tangela_front);
        Drawable tangelaBack = res.getDrawable(R.drawable.tangela_back);
        Move[] tangelaMoves;
        Stats tangelaStats = new Stats(1, 65, 55, 115, 100, 40, 60);
	/*114*/ new Pokemon("Tangela", 35.0, grass, noType, tangelaMoves, tangelaStats, 65, tangelaFront, tangelaBack);
        Drawable kangaskhanFront = res.getDrawable(R.drawable.kangaskhan_front);
        Drawable kangaskhanBack = res.getDrawable(R.drawable.kangaskhan_back);
        Move[] kangaskhanMoves;
        Stats kangaskhanStats = new Stats(1, 105, 95, 80, 40, 80, 90);
	/*115*/ new Pokemon("Kangaskhan", 80.0, normal, noType, kangaskhanMoves, kangaskhanStats,105, kangaskhanFront, kangaskhanBack);
        Drawable horseaFront = res.getDrawable(R.drawable.horsea_front);
        Drawable horseaBack = res.getDrawable(R.drawable.horsea_back);
        Move[] horseaMoves;
        Stats horseaStats = new Stats(1, 30, 40, 70, 70, 25, 60);
	/*116*/ new Pokemon("Horsea", 8.0, water, noType, horseaMoves, horseaStats, 30, horseaFront, horseaBack);
        Drawable seadraFront = res.getDrawable(R.drawable.seadra_front);
        Drawable seadraBack = res.getDrawable(R.drawable.seadra_back);
        Move[] seadraMoves;
        Stats seadraStats = new Stats(1, 55, 65, 95, 95, 45, 85);
	/*117*/ new Pokemon("Seadra", 25.0, water, noType, seadraMoves, seadraStats, 55, seadraFront, seadraBack);
        Drawable goldeenFront = res.getDrawable(R.drawable.goldeen_front);
        Drawable goldeenBack = res.getDrawable(R.drawable.goldeen_back);
        Move[] goldeenMoves;
        Stats goldeenStats = new Stats(1, 45, 67, 60, 35, 50, 63);
	/*118*/ new Pokemon("Goldeen", 15.0, water, noType, goldeenMoves, goldeenStats, 45, goldeenFront, goldeenBack);
        Drawable seakingFront = res.getDrawable(R.drawable.seaking_front);
        Drawable seakingBack = res.getDrawable(R.drawable.seaking_back);
        Move[] seakingMoves;
        Stats seakingStats = new Stats(1, 80, 92, 65, 65, 80, 68);
	/*119*/ new Pokemon("Seaking", 39.0, water, noType, seakingMoves, seakingStats, 80, seakingFront, seakingBack);
        Drawable staryuFront = res.getDrawable(R.drawable.staryu_front);
        Drawable staryuBack = res.getDrawable(R.drawable.staryu_back);
        Move[] staryuMoves;
        Stats staryuStats = new Stats(1, 30, 45, 55, 70, 55, 85);
	/*120*/ new Pokemon("Staryu", 34.5, water, noType,staryuMoves,staryuStats, 30, staryuFront, staryuBack);
        Drawable starmieFront = res.getDrawable(R.drawable.starmie_front);
        Drawable starmieBack = res.getDrawable(R.drawable.starmie_back);
        Move[] starmieMoves;
        Stats starmieStats = new Stats(1, 60, 75, 85, 100, 85, 115);
	/*121*/ new Pokemon("Starmie", 80.0, water, psychic, starmieMoves, starmieStats,60, starmieFront, starmieBack);
        Drawable mr_mimeFront = res.getDrawable(R.drawable.mr_mime_front);
        Drawable mr_mimeBack = res.getDrawable(R.drawable.mr_mime_back);
        Move[] mr_mimeMoves;
        Stats mr_mineStats = new Stats(1, 40, 45, 65, 100, 120, 90);
	/*122*/ new Pokemon("Mr.Mime", 54.4, psychic, fairy, mr_mimeMoves,mr_mineStats, 40, mr_mimeFront, mr_mimeBack);
        Drawable scytherFront = res.getDrawable(R.drawable.scyther_front);
        Drawable scytherBack = res.getDrawable(R.drawable.scyther_back);
        Move[] scytherMoves;
        Stats scytherStats = new Stats(1, 70, 110, 80, 55, 80, 105);
	/*123*/ new Pokemon("Scyther", 56.0, bug, flying, scytherMoves,scytherStats,70, scytherFront,scytherBack);
        Drawable jynxFront = res.getDrawable(R.drawable.jynx_front);
        Drawable jynxBack = res.getDrawable(R.drawable.jynx_back);
        Move[] jynxMoves;
        Stats jynxStats = new Stats(1, 65, 50, 35, 115, 95, 95);
	/*124*/ new Pokemon("Jynx", 40.6, ice, psychic, jynxMoves,jynxStats,65, jynxFront, jynxBack);
        Drawable electrabuzzFront = res.getDrawable(R.drawable.electrabuzz_front);
        Drawable electrabuzzBack = res.getDrawable(R.drawable.electrabuzz_back);
        Move[] electrabuzzMoves;
        Stats electrabuzzStats = new Stats(1, 65, 83, 57, 95, 85, 105);
	/*125*/ new Pokemon("Electrabuxx", 30.0, electric, noType, electrabuzzMoves ,electrabuzzStats,65, electrabuzzFront,electrabuzzBack);
        Drawable magmarFront = res.getDrawable(R.drawable.magmar_front);
        Drawable magmarBack = res.getDrawable(R.drawable.magmar_back);
        Move[] magmarMoves;
        Stats magmarStats = new Stats(1, 65, 95, 57, 100, 85, 93);
	/*126*/ new Pokemon("Magmar",44.5, fire, noType,magmarMoves,magmarStats,65,magmarFront,magmarBack);
        Drawable pinsirFront = res.getDrawable(R.drawable.pinsir_front);
        Drawable pinsirBack = res.getDrawable(R.drawable.pinsir_back);
        Move[] pinsirMoves;
        Stats pinsirStats = new Stats(1, 65, 125, 100, 55, 70, 85);
	/*127*/ new Pokemon("Pinsir",55.0, bug, noType,pinsirMoves,pinsirStats,65,pinsirFront,pinsirBack);
        Drawable taurosFront = res.getDrawable(R.drawable.tauros_front);
        Drawable taurosBack = res.getDrawable(R.drawable.tauros_back);
        Move[] taurosMoves;
        Stats taurosStats = new Stats(1, 75, 100, 95, 40, 70, 110);
	/*128*/ new Pokemon("Tauros",88.4, normal, noType,taurosMoves,taurosStats,75,taurosFront,taurosBack);
        Drawable magikarpFront = res.getDrawable(R.drawable.magikarp_front);
        Drawable magikarpBack = res.getDrawable(R.drawable.magikarp_back);
        Move[] magikarpMoves;
        Stats magikarpStats = new Stats(1, 20, 10, 55, 15, 20, 80);
	/*129*/ new Pokemon("Magicharp",10.0, water, noType,magikarpMoves,magikarpStats,20,magikarpFront,magikarpBack);
        Drawable gyaradosFront = res.getDrawable(R.drawable.gyarados_front);
        Drawable gyaradosBack = res.getDrawable(R.drawable.gyarados_back);
        Move[] gyaradosMoves;
        Stats gyaradosStats = new Stats(1, 95, 125, 79, 60, 100, 81);
	/*130*/ new Pokemon("Gyarados",235.0, water, flying,gyaradosMoves,gyaradosStats,95,gyaradosFront,gyaradosBack);
        Drawable laprasFront = res.getDrawable(R.drawable.lapras_front);
        Drawable laprasBack = res.getDrawable(R.drawable.lapras_back);
        Move[] laprasMoves;
        Stats laprasStats = new Stats(1, 130, 85, 80, 85, 95, 60);
	/*131*/ new Pokemon("Lapras",220.0, water, ice,laprasMoves,laprasStats,130,laprasFront,laprasBack);
        Drawable dittoFront = res.getDrawable(R.drawable.ditto_front);
        Drawable dittoBack = res.getDrawable(R.drawable.ditto_back);
        Move[] dittoMoves;
        Stats dittoStats = new Stats(1, 45, 45, 45, 45, 45, 45);
	/*132*/ new Pokemon("Ditto",4.0, normal, noType,dittoMoves,dittoStats,48,dittoFront,dittoBack);
        Drawable eeveeFront = res.getDrawable(R.drawable.eevee_front);
        Drawable eeveeBack = res.getDrawable(R.drawable.eevee_back);
        Move[] eeveeMoves;
        Stats eeveeStats = new Stats(1, 55, 55, 50, 45, 65, 55);
	/*133*/ new Pokemon("Eevee",6.5, normal, noType,eeveeMoves,eeveeStats,55,eeveeFront,eeveeBack);
        Drawable vaporeonFront = res.getDrawable(R.drawable.vaporeon_front);
        Drawable vaporeonBack = res.getDrawable(R.drawable.vaporeon_back);
        Move[] vaporeonMoves;
        Stats vaporeonStats = new Stats(1, 130, 65, 60, 110, 95, 65);
	/*134*/ new Pokemon("Vaporeon",29.0, water, noType,vaporeonMoves,vaporeonStats,130,vaporeonFront,vaporeonBack);
        Drawable jolteonFront = res.getDrawable(R.drawable.jolteon_front);
        Drawable jolteonBack = res.getDrawable(R.drawable.jolteon_back);
        Move[] jolteonMoves;
        Stats jolteonStats = new Stats(1, 65, 65, 60, 110, 95, 130);
	/*135*/ new Pokemon("Jolteon", 24.5, electric, noType,jolteonMoves,jolteonStats,65,jolteonFront,jolteonBack);
        Drawable flareonFront = res.getDrawable(R.drawable.flareon_front);
        Drawable flareonBack = res.getDrawable(R.drawable.flareon_back);
        Move[] flareonMoves;
        Stats flareonStats = new Stats(1, 65, 130, 60, 95, 110, 65);
	/*136*/ new Pokemon("Flareon",25.0, fire, noType,flareonMoves,flareonStats,65, flareonFront,flareonBack);
        Drawable porygonFront = res.getDrawable(R.drawable.porygon_front);
        Drawable porygonBack = res.getDrawable(R.drawable.porygon_back);
        Move[] porygonMoves;
        Stats porygonStats = new Stats(1, 65, 60, 70, 85, 75, 40);
	/*137*/ new Pokemon("Porygon",36.5, normal, noType,porygonMoves,porygonStats,65,porygonFront,porygonBack);
        Drawable omanyteFront = res.getDrawable(R.drawable.omanyte_front);
        Drawable omanyteBack = res.getDrawable(R.drawable.omanyte_back);
        Move[] omanyteMoves;
        Stats omanyteStats = new Stats(1, 35, 40, 100, 90, 55, 35);
	/*138*/ new Pokemon("Omanyte", 7.5, rock, water, omanyteMoves,omanyteStats,35,omanyteFront,omanyteBack);
        Drawable omastarFront = res.getDrawable(R.drawable.omastar_front);
        Drawable omastarBack = res.getDrawable(R.drawable.omastar_back);
        Move[] omastarMoves;
        Stats omastarStats = new Stats(1, 70, 60, 125, 115, 70, 55);
	/*139*/ new Pokemon("Omastar", 35.0, rock, water,omastarMoves,omastarStats, 70, omastarFront,omastarBack);
        Drawable kabutoFront = res.getDrawable(R.drawable.kabuto_front);
        Drawable kabutoBack = res.getDrawable(R.drawable.kabuto_back);
        Move[] kabutoMoves;
        Stats kabutoStats = new Stats(1, 30, 80, 90, 55, 45, 55);
	/*140*/ new Pokemon("Kabuto", 11.5, rock, water,kabutoMoves,kabutoStats,30, kabutoFront,kabutoBack);
        Drawable kabutopsFront = res.getDrawable(R.drawable.kabutops_front);
        Drawable kabutopsBack = res.getDrawable(R.drawable.kabutops_back);
        Move[] kabutopsMoves;
        Stats kabutopsStats = new Stats(1, 60, 15, 105, 65, 70, 80);
	/*141*/ new Pokemon ("Kabutops", 40.5, rock, water,kabutopsMoves,kabutopsStats,60,kabutopsFront,kabutopsBack);
        Drawable aerodactylFront = res.getDrawable(R.drawable.aerodactyl_front);
        Drawable aerodactylBack = res.getDrawable(R.drawable.aerodactyl_back);
        Move[] aerodactylMoves;
        Stats aerodactylStats = new Stats(1, 80, 105, 65, 60, 75, 130);
	/*142*/ new Pokemon("Aerodactyl", 59.0, rock, flying,aerodactylMoves, aerodactylStats,80, aerodactylFront,aerodactylBack);
        Drawable snorlaxFront = res.getDrawable(R.drawable.snorlax_front);
        Drawable snorlaxBack = res.getDrawable(R.drawable.snorlax_back);
        Move[] snorlaxMoves;
        Stats snorlaxStats = new Stats(1, 160, 110, 65, 65, 110, 30);
	/*143*/ new Pokemon("Snorlax",460.0, normal, noType,snorlaxMoves,snorlaxStats,160,snorlaxFront,snorlaxBack);
        Drawable articunoFront = res.getDrawable(R.drawable.articuno_front);
        Drawable articunoBack = res.getDrawable(R.drawable.articuno_back);
        Move[] articunoMoves;
        Stats articunoStats = new Stats(1, 90, 85, 100, 95, 125, 85);
	/*144*/ new Pokemon("Articuno", 55.4 ,ice, flying,articunoMoves,articunoStats,90,articunoFront,articunoBack);
        Drawable zapdosFront = res.getDrawable(R.drawable.zapdos_front);
        Drawable zapdosBack = res.getDrawable(R.drawable.zapdos_back);
        Move[] zapdosMoves;
        Stats zapdosStats = new Stats(1, 90, 90, 85, 125, 90, 100);
	/*145*/ new Pokemon("Zapdos", 52.6 , electric, flying,zapdosMoves,zapdosStats,90,zapdosFront,zapdosBack);
        Drawable moltresFront = res.getDrawable(R.drawable.moltres_front);
        Drawable moltresBack = res.getDrawable(R.drawable.moltres_back);
        Move[] moltresMoves;
        Stats moltressStats = new Stats(1, 90, 100, 90, 125, 85, 90);
	/*146*/ new Pokemon("Moltres", 60.0, fire, flying,moltresMoves,moltressStats,90,moltresFront,moltresBack);
        Drawable dratiniFront = res.getDrawable(R.drawable.dratini_front);
        Drawable dratiniBack = res.getDrawable(R.drawable.dratini_back);
        Move[] dratiniMoves;
        Stats dratiniStats = new Stats(1, 41, 64, 45, 50, 50, 50);
	/*147*/ new Pokemon("Dratini", 3.3, dragon, noType,dratiniMoves,dratiniStats,41,dratiniFront,dratiniBack);
        Drawable dragonairFront = res.getDrawable(R.drawable.dragonair_front);
        Drawable dragonairBack = res.getDrawable(R.drawable.dragonair_back);
        Move[] dragonairMoves;
        Stats dragonairStats =  new Stats(1, 61, 84, 65, 70, 70, 70);
	/*148*/ new Pokemon("Dragonair", 16.5, dragon, noType,dragonairMoves,dragonairStats,61,dragonairFront,dragonairBack);
        Drawable dragoniteFront = res.getDrawable(R.drawable.dragonite_front);
        Drawable dragoniteBack = res.getDrawable(R.drawable.dragonite_back);
        Move[] dragoniteMoves;
        Stats dragoniteStats = new Stats(1, 91, 134, 95, 100, 100, 80);
	/*149*/ new Pokemon("Dragonite", 210.0, dragon, flying,dragoniteMoves,dragoniteStats,91,dragoniteFront,dragoniteBack);
        Drawable mewtwoFront = res.getDrawable(R.drawable.mewtwo_front);
        Drawable mewtwoBack = res.getDrawable(R.drawable.mewtwo_back);
        Move[] mewtwoMoves;
        Stats mewtwoStats =  new Stats(1, 106, 110, 90, 154, 90, 130);
	/*150*/ new Pokemon("Mewtwo", 122.0,psychic, noType,mewtwoMoves,mewtwoStats, 106,mewtwoFront,mewtwoBack);
        Drawable mewFront = res.getDrawable(R.drawable.mew_front);
        Drawable mewBack = res.getDrawable(R.drawable.mew_back);
        Move[] mewMoves;
        Stats mewStats = new Stats(1, 100, 100, 100, 100, 100, 100);
	/*151*/ new Pokemon("Mew", 4.0, psychic, noType, mewMoves, mewStats, 100, mewFront, mewBack);
    }
}
